// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8XaMQ2JCZh0r7xhfMSvUcUnqlRpNJ-2Y',
    appId: '1:922941791257:web:6fd1eff4e5e29115209e88',
    messagingSenderId: '922941791257',
    projectId: 'cartfly-4382a',
    authDomain: 'cartfly-4382a.firebaseapp.com',
    storageBucket: 'cartfly-4382a.firebasestorage.app',
    measurementId: 'G-HZTR32N76R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvPHZtbtoKvUUVzvKW55kz4-yNj3D6VJM',
    appId: '1:922941791257:android:076962cc031c91b3209e88',
    messagingSenderId: '922941791257',
    projectId: 'cartfly-4382a',
    storageBucket: 'cartfly-4382a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK3tp7-_lNjst17SQKYfl0qmqsPG0cjxs',
    appId: '1:922941791257:ios:83e65469a560effb209e88',
    messagingSenderId: '922941791257',
    projectId: 'cartfly-4382a',
    storageBucket: 'cartfly-4382a.firebasestorage.app',
    iosBundleId: 'com.example.cartfly',
  );
}
